<?php

return array (
  'name' => '我的网站',
  'beian' => '',
  'cdnurl' => '',
  'version' => '1.0.1',
  'timezone' => 'Asia/Shanghai',
  'forbiddenip' => '',
  'languages' => 
  array (
    'backend' => 'zh-cn',
    'frontend' => 'zh-cn',
  ),
  'fixedpage' => 'dashboard',
  'categorytype' => 
  array (
    'default' => 'Default',
    'page' => 'Page',
    'article' => 'Article',
    'test' => 'Test',
  ),
  'configgroup' => 
  array (
    'basic' => 'Basic',
    'email' => 'Email',
    'dictionary' => 'Dictionary',
    'user' => 'User',
    'example' => 'Example',
  ),
  'mail_type' => '1',
  'mail_smtp_host' => 'smtp.qq.com',
  'mail_smtp_port' => '465',
  'mail_smtp_user' => '10000',
  'mail_smtp_pass' => 'password',
  'mail_verify_type' => '2',
  'mail_from' => '10000@qq.com',
  'ykc' => '2',
  'zcc' => '2',
  'djgg' => '2',
  'mrgk' => '2',
  'erm' => '2',
  'ggg' => '<p style="line-height: 1.2;"><span style="font-size: 14px;">最新官网</span><a href="http://htsq98.vip/" target="_blank">http://jssq.tv/</a><span style="font-size: 14px;">，请各位老铁详记最新地址，若软件有什么问题可以重新下载，几十万部成人视频秒播给你最高享受，使用过程中如有任何问题可以及时留言咨询</span></p><p style="line-height: 1.2;"><span style="font-size: 14px;">请勿相信任何转账信息，如有问题请联系在线客</span></p>',
  'fxlj' => '華人聚集的成人互動社區，海量精品成人資源等妳來看，讓聚色社區成為妳值得留戀的壹款APP:http://huatang.xyz/',
  'tvideo' => '2',
  'integral_one' => '0',
  'integral_two' => '100',
  'integral_three' => '200',
  'rebate_one' => '5',
  'rebate_two' => '8',
  'rebate_three' => '15',
  'agent_one' => '20%',
  'agent_two' => '30%',
  'agent_three' => '50%',
  'gdt' => '请勿相信任何转账信息，如有问题咨询在线客服！商务Telegram：',
  'allowfree' => '1',
  'pay' => '1',
  'website' => 'http://www.jssq.tv/h5',
  'direct' => '严正声明：    请勿相信任何直播间广告，花堂社区没有赌博广告，没有卖片广告更不提供任何线下约炮活动，任何主播与堂主私加联系方式属于个人行为，造成的任何后果自行承担与本平台无关！',
  'video_prefix' => 'https://aev.h-shops.com',
  'chat' => 'http://www.mfkefu.com/chat-11.html?from=pcwin',
);